"""
Power-conversion losses and auxiliary load — the part most revenue models omit.

Public battery revenue models almost always carry a single round-trip efficiency,
typically 0.9, applied uniformly. Two things are wrong with that.

First, converter efficiency is a function of load. Loss in a power-electronic
converter has a fixed component (gate drive, control, magnetics excitation), a
component roughly linear in current, and a conduction component roughly quadratic
in current. At rated power the fixed part is negligible and efficiency is high; at
10 % load the same fixed loss is ten times larger relative to throughput and
efficiency collapses. Field measurement of a utility-scale BESS in southern Italy
reports system efficiency near 85 % at full power falling to about 65 % at low
power (doi:10.1016/j.est.2023.107232). A constant 0.9 is therefore optimistic
everywhere and badly optimistic in the shallow-cycling regimes that frequency
services actually operate in.

Second, thermal management draws power continuously. It is not part of round-trip
efficiency at all: it runs whether or not the battery is cycling, and it scales
with ambient conditions and with the heat generated by cycling. Omitting it does
not distort dispatch much, but it silently inflates net revenue.

The loss model here is
    P_loss(P) = p_fixed * P_rated + k1 * P + k2 * P^2 / P_rated
which is convex in P. Convexity matters: it lets the loss enter a linear program
exactly, as the upper envelope of its tangent lines, with no binaries and no
piecewise ordering constraints.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass
class ConverterModel:
    """Load-dependent converter efficiency, calibrated to two observed points."""
    p_rated_mw: float = 50.0
    eta_at_rated: float = 0.922        # one-way; 0.922^2 ~ 0.85 round trip
    eta_at_low: float = 0.806          # one-way at low_load_frac; 0.806^2 ~ 0.65
    low_load_frac: float = 0.10
    aux_standing_mw: float = 0.0       # thermal management, always on
    aux_per_mwh: float = 0.0           # extra auxiliary energy per MWh cycled

    def __post_init__(self):
        # Solve p_fixed, k1, k2 from the two efficiency points plus the requirement
        # that marginal loss stays non-negative at zero load.
        # loss(P) = f*Pr + k1*P + k2*P^2/Pr ;  eta(P) = P / (P + loss(P))
        pr = self.p_rated_mw
        l_rated = pr * (1.0 / self.eta_at_rated - 1.0)
        p_low = self.low_load_frac * pr
        l_low = p_low * (1.0 / self.eta_at_low - 1.0)
        # two equations, three unknowns: fix k1 = 0 and let the fixed and quadratic
        # terms carry the shape. This reproduces the classic converter loss split
        # (no-load loss plus conduction loss) and matches both calibration points.
        # l_low = f*pr + k2*p_low^2/pr ; l_rated = f*pr + k2*pr
        k2 = (l_rated - l_low) / (pr - p_low ** 2 / pr)
        f = (l_rated - k2 * pr) / pr
        self.p_fixed, self.k1, self.k2 = float(f), 0.0, float(k2)

    def loss_mw(self, p_mw, variable_only: bool = False):
        """Converter loss. `variable_only` drops the no-load term, which is carried
        separately as a standing draw so that the optimiser stays linear (a
        load-independent loss would otherwise need an on/off binary)."""
        p = np.asarray(p_mw, dtype=float)
        var = self.k1 * p + self.k2 * p ** 2 / self.p_rated_mw
        return var if variable_only else self.p_fixed * self.p_rated_mw + var

    @property
    def fixed_loss_mw(self) -> float:
        """No-load loss, to be applied as standing auxiliary draw."""
        return self.p_fixed * self.p_rated_mw

    def efficiency(self, p_mw):
        p = np.asarray(p_mw, dtype=float)
        with np.errstate(divide="ignore", invalid="ignore"):
            e = np.where(p > 1e-9, p / (p + self.loss_mw(p)), np.nan)
        return e

    def round_trip(self, p_mw):
        e = self.efficiency(p_mw)
        return e ** 2

    def tangents(self, n: int = 6):
        """Tangent lines to the convex loss curve, for exact LP representation.

        Returns (slope, intercept) pairs such that loss(P) = max_j (a_j P + b_j).
        The fixed loss is deliberately excluded here — it is only incurred when the
        converter is running, which would need a binary. It is applied instead as
        part of the standing auxiliary load, which is the physically honest place
        for it in a system that keeps its auxiliaries energised.
        """
        pr = self.p_rated_mw
        pts = np.linspace(0.05 * pr, pr, n)
        out = []
        for p0 in pts:
            slope = self.k1 + 2 * self.k2 * p0 / pr
            val = self.k1 * p0 + self.k2 * p0 ** 2 / pr
            out.append((float(slope), float(val - slope * p0)))
        return out

    def summary(self) -> dict:
        pts = np.array([0.05, 0.1, 0.25, 0.5, 0.75, 1.0]) * self.p_rated_mw
        return {"load_frac": (pts / self.p_rated_mw).round(2).tolist(),
                "one_way_efficiency": self.efficiency(pts).round(3).tolist(),
                "round_trip": self.round_trip(pts).round(3).tolist(),
                "p_fixed_frac_of_rated": round(self.p_fixed, 5),
                "k2": round(self.k2, 5)}


if __name__ == "__main__":
    c = ConverterModel()
    s = c.summary()
    print("load frac :", s["load_frac"])
    print("one-way   :", s["one_way_efficiency"])
    print("round trip:", s["round_trip"])
    print("fixed loss as fraction of rated power:", s["p_fixed_frac_of_rated"])
    print("\nconstant-0.9 assumption overstates round-trip efficiency by:")
    for lf, rt in zip(s["load_frac"], s["round_trip"]):
        print(f"  at {lf:4.0%} load: {0.9 - rt:+.3f} ({(0.9/rt - 1)*100:+.1f} %)")
